model:
    name: 'SelfSupModel'
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
datasets:
    augmentation:
        image_shape: (384, 640)
    test:
        dataset: ['DGP']
        path: ['/home/thuar/Desktop/baseline_packnet_selfsup/data/DDAD_tiny/ddad_tiny.json']
        split: ['val']
        depth_type: ['lidar']
        cameras: [['camera_01']]
save:
    folder: '/home/thuar/Desktop/kitti_pre_trained_model/data/save'
    depth:
        rgb: True
        viz: True
        npz: True
        png: True
